External table support for scenario
getgauge/gauge pull request #1720
Opened 2020-08-19 06:48 UTC by BugDiver

Fixes #1714

2020-08-25 12:15 UTC, sriv requested changes

2020-08-28 10:43 UTC, sriv approved these changes

2020-08-31 02:57 UTC, merged

2021-09-30 21:11 UTC, bansal63 commented
@BugDiver @sriv 
Is there an example on how external table support works for a scenario?

Right now we are using https://docs.gauge.org/writing-specifications.html?os=macos&language=javascript&ide=vscode#table-driven-scenario. 
With are we saying table can be moved out into a csv?

2021-09-30 21:50 UTC, bansal63 commented
Hi @BugDiver @sriv 
It would be great if documentation also gets updated here.